# Generated by Django 4.0.3 on 2022-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_irobot_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facestore',
            name='sync_state',
            field=models.IntegerField(default=0, verbose_name='与设备同步状态'),
        ),
    ]
