# Generated by Django 4.0.3 on 2022-03-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_irobot_main', '0002_facestore_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='facestore',
            name='client_sync_list',
            field=models.CharField(default='[]', max_length=100, verbose_name='设备同步列表'),
        ),
    ]
