# Generated by Django 4.0.3 on 2022-03-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassInfo',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='员工id')),
                ('company_id', models.IntegerField(default=999, verbose_name='企业id')),
                ('pass_time', models.DateTimeField(verbose_name='通行时间')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('client_user', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='设备唯一号')),
                ('client_key', models.CharField(max_length=20, verbose_name='设备认证密码')),
                ('client_token', models.CharField(default='', max_length=50, verbose_name='设备token')),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to='admin_manage.admin', verbose_name='设备企业信息')),
            ],
        ),
    ]
