# Generated by Django 4.0.3 on 2022-03-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_machine_client', '0002_alter_clientinfo_client_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50, verbose_name='同步类型')),
                ('sync_state', models.CharField(max_length=10, verbose_name='同步状态')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_info', to='face_machine_client.clientinfo')),
            ],
        ),
    ]
