# Generated by Django 4.0.3 on 2022-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_machine_client', '0003_syncinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncinfo',
            name='face_data_len',
            field=models.IntegerField(default=0, verbose_name='人脸数据长度'),
        ),
        migrations.AddField(
            model_name='syncinfo',
            name='success_sync',
            field=models.IntegerField(default=0, verbose_name='成功下发数量'),
        ),
    ]
