# Generated by Django 4.0.3 on 2022-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_machine_client', '0005_passinfo_id_alter_passinfo_pass_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passinfo',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
