# Generated by Django 4.0.3 on 2022-03-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_machine_client', '0007_alter_passinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passinfo',
            name='pass_time',
            field=models.DateTimeField(verbose_name='通行时间'),
        ),
    ]
