# Generated by Django 4.0.3 on 2022-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_machine_client', '0008_alter_passinfo_pass_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='passinfo',
            name='client_user',
            field=models.CharField(default='empty', max_length=30, verbose_name='设备号'),
        ),
    ]
